openapi: '3.0.2'
info:
  title: final-project-backend-api
  version: '1.0'
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Hello World endpoint
      description: This endpoint can be used to test that the server is responding correctly.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: |
                {"message": "Hello World!"}
  /user:
    get:
      responses:
        '200':
          description: OK
