openapi: '3.0.2'
info:
  title: final-project-backend-api
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /user:
    get:
      responses:
        '200':
          description: OK
