openapi: '3.0.2'
info:
  title: final-project-backend-api
  version: '1.0'
  description: |
    ## 6.1040 Final Project OpenAPI Spec
servers:
  - url: http://127.0.0.1:8080
    description: Development
  - url: https://6-1040-final-project.vercel.app
    description: Production
paths:
  /api:
    get:
      summary: Hello World endpoint
      description: This endpoint can be used to test that the server is responding correctly.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                message: "Hello World!"
  /api/users/token-sign-in:
    post:
      summary: Google Auth Token sign in
      description: Use Google OAuth2 for authentication and send basic profile information to backend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id_token:
                  type: string
      responses:
        '201':
          description: 'OK'
          content:
            application/json:
              example:
                type: object
                properties:
                  message: "You have signed in successfully."
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: string
    
