openapi: '3.0.2'
info:
  title: final-project-backend-api
  version: '1.0'
  description: |
    ## 6.1040 Final Project OpenAPI Spec
servers:
  - url: http://127.0.0.1:8080
    description: Development
  - url: https://6-1040-final-project.vercel.app
    description: Production
paths:
  /api:
    get:
      summary: Hello World endpoint
      description: This endpoint can be used to test that the server is responding correctly.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                message: "Hello World!"
  /api/users/session/token-auth:
    $ref: "./paths/users.yml#/PATH_users-gapi-token-auth"
  /api/users/session:
    $ref: "./paths/users.yml#/PATH_users-session"
  /api/users:
    $ref: "./paths/users.yml#/PATH_users"
  /api/spaces:
    $ref: "./paths/spaces.yml#/PATH_spaces"
  /api/requests/{place_id}:
    $ref: "./paths/requests.yml#/PATH_requests_post"
  /api/requests:
    $ref: "./paths/requests.yml#/PATH_requests"
  /api/checkins/session/{place_id}:
    $ref: "./paths/checkins.yml#/PATH_checkin_session"
  /api/checkins/today/session/{place_id}:
    $ref: "./paths/checkins.yml#/PATH_checkin_today_session"
  /api/checkins:
    $ref: "./paths/checkins.yml#/PATH_checkin"
  /api/checkins/count/{place_id}:
    $ref: "./paths/checkins.yml#/PATH_checkin_counts"
  /api/replies/{request_id}:
    $ref: "./paths/replies.yml#/PATH_replies_post"
  /api/replies:
    $ref: "./paths/replies.yml#/PATH_replies"
components:
  schemas:
    $ref: "./schemas/_index.yml"
